name: 'CI'
on:
- 'push'
jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: 'actions/checkout@v1'
    - uses: 'mstksg/setup-stack@v1'
    - uses: 'actions/cache@v1'
      with:
        path: '$HOME/.stack'
        key: "${{ runner.os }}-v2-stack-${{ hashFiles('stack.yaml.lock') }}"
        restore-keys: '${{ runner.os }}-v2-stack'
    - run: 'stack build --test'
